import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const soehneHalbfett = localFont({
  src: "./test-soehne-halbfett.woff2",
  display: "swap",
  variable: '--font-soehne-halbfett'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${soehneHalbfett.variable} px-3 py-4 bg-white font-sans`}>{children}</body>
    </html>
  );
}
